baseURL = 'https://rinconjc.github.io/blog/'
languageCode = 'en-us'
title = 'The Journey'
disqusShortname = 'disqus_sm39zaPQNu' 

[module]
    [[module.imports]]
    path = "github.com/halogenica/beautifulhugo"

[markup.goldmark.renderer]
    unsafe = true


[params]
    comments = true