baseURL = 'http://rinconjc.github.io/blog/'
languageCode = 'en-us'
title = 'The Journey'

[module]
    [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
    unsafe = true