baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'The Journey'

[module]
    [[module.imports]]
        path = "github.com/adityatelange/hugo-PaperMod"

theme = "PaperMod"

[markup.goldmark.renderer]
    unsafe = true